### ISSUE TITLE
artelad can't work

### ISSUE THREAD

**Issue by sleeply7777** [artela-network/artela#111]
the error is 
`error while loading shared libraries: libaspect_wasm_instrument.so: cannot open shared object file: No such file or directory`
after run `make clean && make && ./build/artelad -h `

**Comment by dumbeng** [comment]
Hello, if you're looking to participate in the Artela testnet today (May 16th), please note that you'll need to compile the code using version v0.4.7-rc6, not the head of main branch. The main branch is currently at version v0.47.0-rc7 and has not yet been upgraded to support the Artela testnet.

If you do require code compilation for version v0.4.7-rc7, you'll need to download the shared object file and append its path to the LD_LIBRARY_PATH variable, similar to the following:
export LD_LIBRARY_PATH=/path/to/library:$LD_LIBRARY_PATH
You can find shared object file here:
https://github.com/artela-network/aspect-runtime/tree/v0.4.7-rc7/instrument/build

**Comment by sleeply7777** [comment]
thx
