### ISSUE TITLE
run artelad failed

### ISSUE THREAD

**Issue by lesywix** [artela-network/artela#113]
# Describe the bug
When I try to run artelad after make install, it shows the artelad: error while loading shared libraries: libaspect_wasm_instrument.so: cannot open shared object file: No such file or directory error.

# To reproduce

1. Go to artela git dir
2. run make install
3. run artelad

**Comment by luketheart** [comment]
please refer to https://github.com/artela-network/artela/issues/109#issuecomment-2114046285

**Comment by lesywix** [comment]
Got it, closed the issue, thx
