### ISSUE TITLE
Connect: connection refused

### ISSUE THREAD

**Issue by chenhonghe** [artela-network/artela#143]
10:28AM DBG Dialing peer address={"id":"9e2fbfc4b32a1b013e53f3fc9b45638f4cddee36","ip":"47.254.66.177","port":26656} module=p2p
10:28AM INF error from light block request from primary, removing... error="post failed: Post \"http://47.254.66.177:26657\": dial tcp 47.254.66.177:26657: connect: connection refused" height=114011 module=light primary={}
10:28AM ERR error on light block request from witness, removing... error="post failed: Post \"http://47.89.230.117:26657\": dial tcp 47.89.230.117:26657: connect: connection refused" module=light primary={}
10:28AM ERR failed to remove witnesses err="no witnesses connected. please reset light client" module=light witnessesToRemove=[0]
Error: failed to start state sync: failed to set up light client state provider: post failed: Post "http://47.89.230.117:26657": dial tcp 47.89.230.117:26657: connect: connection refused

config.toml

# Comma separated list of seed nodes to connect to
seeds = "9e2fbfc4b32a1b013e53f3fc9b45638f4cddee36@47.254.66.177:26656,30fb0055aced21472a01911353101bc4cd356bb3@47.89.230.117:26656"

**Comment by chenhonghe** [comment]
In addition to the three in https://docs.artela.network/develop/node/access-testnet#public-information-on-testnet, what other RPC servers are there?

**Comment by LukeNinjaX** [comment]
All known peers are in addrbook, replace your local addrbook and wait patiently for the node to automatically connect to the available peers.

**Comment by LukeNinjaX** [comment]
Close due to in-activity.
