### ISSUE TITLE
Change x

### ISSUE THREAD

**Issue by Arinomama22** [artela-network/artela#151]
Some of my friends want to ask about changing or replacing their x accounts, because many have been suspended and I tried it myself but it doesn't work via mobile.
![IMG_20240720_132706](https://github.com/user-attachments/assets/11262ee3-8031-491d-8b22-b4855340150a)

**Comment by LukeNinjaX** [comment]
Please ask about Renaissance in the Discord channel: https://discord.com/channels/1143699396500934796/1242322885633118218.

**Comment by Arinomama22** [comment]
Thanks
