### ISSUE TITLE
Failed to clone

### ISSUE THREAD

**Issue by realrufans** [artela-network/artela#89]
![image](https://github.com/artela-network/artela/assets/33923021/63e9272f-fcee-4a2a-b4fe-23c5666f4ef0)

**Comment by gene-zhan** [comment]
<img width="603" alt="image" src="https://github.com/artela-network/artela/assets/125658572/5f487a96-9cc8-46ed-9520-09ff369f74a4">
I haven't encountered similar issues in my local testing.Try switching to a different local network environment and see if that helps.

**Comment by realrufans** [comment]
I have a friend who uses Linux but it failed on hers, then I tried on windows and it also failed.  But I will retry later today with Ubuntu. Thanks for the response.
